services:
  db:
    build:
      context: ./db
    container_name: learning101_db
    ports:
      - "5433:5432"
    volumes:
      - learning101_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  learning101_db_data: